add_newline = true

[username]
show_always = true
format = "[$user ](italic purple)"

[directory]
format = "[$path](italic bold cyan) "
truncation_length = 6

[cmd_duration]
disabled = true

[jobs]
disabled = true
