---

- name: Install flatpak
  become: true
  dnf:
    name: flatpak
    state: present

- name: Enable flathub
  become: true
  community.general.flatpak:
    state: present
    name:  https://flathub.org/repo/flathub.flatpakrepo

# - name: Install Flatpak Applications
#   community.general.flatpak:
#     state: present
#     name: {{ item }}
#   loop:
#     - com.spotify.Client
#     - com.discordapp.Discord
#     - com.github.tchx84.Flatseal
#     - dev.lapce.Lapce
#     - com.github.GradienceTeam.Gradience
#     - md.obsidian.Obsidian
