---
- name: Install Gnome Tweak Tooling
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "gnome-tweaks-app"
    - "gnome-extensions"
    - "neofetch"
    - "@development-tools"

- name: Install Gnome Extensions
  become: true
  dnf:
    name: "{{ item }}"
    state: present

  loop:
