---
- name: Import VSCode Repo GPG
  become: true
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Copy VSCode Repo
  become: true
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo

- name: Download updates
  dnf:
    update_cache: true
    name: ""

- name: Install Visual Studio Code
  become: true
  dnf:
    state: present
    name: code

# TODO: review modern extensions in use. 
- name: Install Visual Studio Code extensions
  shell: code --install-extension {{ item }}
  loop:
    - bungcip.better-toml
    - doggy8088.quicktype-refresh
    - golang.go
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - rust-lang.rust-analyzer
    - Tyriar.sort-lines
    - wayou.vscode-todo-highlight
    - yzhang.markdown-all-in-one
    - rastikerdar.vscode-seedling-icon-theme

- name: Create Development Directory
  file:
    path: ~/Developer
    state: directory
