---
- name: Install CLI Tooling
  become: true
  dnf:
    name:
      - "bat"
      - "exa"
      - "fish"
      - "git"
      - "git-delta"
      - "starship"
      - "tmux"
      - "neovim"
      - "starship"
    state: "present"

- name: Create Configuration Directories
  file:
    dest: "~/.config/{{ item }}"
    state: "directory"
  loop:
    - "bat/themes"
    - "fish/conf.d"
    - "fish/functions"
    - "git"
    - "nvim"
    - "tmux"
    - "starship"

# Neovim Setup
- name: Neovim Configuration
  copy:
    src: "neovim/init.lua"
    dest: "~/.config/nvim/init.lua"

- name: Neovim Packer Package Manager
  git: 
    repo: https://github.com/wbthomason/packer.nvim
    dest:  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

# Bat Setup
- name: Bat - Copy Configuration
  copy:
    src: "bat/config"
    dest: "~/.config/bat/config"
    mode: "0644"

- name: Bat - Copy Themes
  copy:
    src: "{{ item }}"
    dest: "~/.config/bat/themes/"
    mode: "0644"
  with_fileglob: "bat/*.tmTheme"

- name: Bat - Build Cache
  shell: "bat cache --build"

# Fish Setup
- name: Fish - Copy Configuration
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/conf.d/{{ item | basename }}"
  with_fileglob: "fish/conf.d/*"

- name: Fish - Copy Completion
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/completions/{{ item | basename }}"
  with_fileglob: "fish/completions/*"

- name: Fish - Copy User Functions
  copy:
    src: "{{ item }}"
    dest: "~/.config/fish/functions/{{ item | basename }}"
  with_fileglob: "fish/functions/*"

- name: Fish - Set User Shell
  become: true
  user:
    name: "raygervais"
    shell: "/usr/bin/fish"

# Tmux Setup
- name: Tmux - Copy Configuration
  copy:
    src: "tmux/tmux.conf"
    dest: "~/.config/tmux/tmux.conf"

# Git Setup
- name: Git - Copy Config
  copy:
    src: "{{ item }}"
    dest: "~/.config/{{ item }}"
  loop:
    - "git/config"
    - "git/ignore"

# Conigure Tomorrow Night Theme via Gogh.sh
- name: Clone gogh
  git:
    repo: https://github.com/Gogh-Co/Gogh
    dest: /tmp/gogh

- name: setup Tomorrow Night theme
  shell: TERMINAL=gnome-terminal /tmp/gogh/themes/tomorrow-night.sh

# Bash Clean Up
- name: Delete Bash Dotfiles
  file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "~/.bash_history"
    - "~/.bash_logout"
    - "~/.bash_profile"
    - "~/.bashrc"
